### PR TITLE
Add keyword to allow flagging of pixels below median

### PR DESCRIPTION
**Pull request by bhilbert4**
In experimenting with using rcselfcal to flag bad pixels in NIRCam, I've found that there is a small population of pixels with signals well below the median that it would be helpful to flag.

You already had a commented out line for flagging pixels below the median. This PR just adds a keyword to toggle this line on and off, and sets the default to be False.

### CODE REVIEW

**Comment by jdavies-st** [comment]
This looks great!  Could you rebase against master?  I did a little cleanup for the next release, which includes renaming this step and changing the source code filename.  `RcSelfCal` -> `OpenPixelStep`

Btw, how stable are these open pixels?  Is it possible to just flag these in the flats, or is there too much structure in the flats to find them at this low level, and it's better to flag them in flattened sky/zodi fields?

**Comment by jdavies-st** [comment]
Oh, and are the pixels below the median level the "center" OPEN pixel and those above the median level the ADJ_OPEN flagged?

Btw, we see these same artifacts on the NISP detectors on board Euclid.  Euclid folks call them "flowers", as they look like tulips.

After some discussion with the Euclid NISP folks and seeing how they're detecting and tracking them, I'm thinking about using a 2D laplace kernel to make them stand out more.  Something like:

```
[[0,  1, 0],
 [1, -4, 1],
 [0,  1, 0]]
```

Thoughts?

**Comment by jdavies-st** [comment]
Nevermind, I added a commit, checks pass.  Merging.

**Comment by bhilbert4** [comment]
I know a closed PR isn't the best place for a discussion, but just for completeness:

I'm not sure if the low pixels will be found in the flats. I can take a look, but I figure as long as we're here flagging the high pixels, it's minimal effort to flag the low ones. NIRCam also doesn't have a lamp, so updating flats is on a slow cadence given that they need to be built up from on sky observations.

The typical definition of OPEN pixels that we've used is that open pixels have zero signal. Everything leaks out to neighboring pixels. So in that sense this pixels aren't open. But in practical terms, it might be ok to label them as open. I haven't looked exhaustively at the neighbors to see if they have abnormally high signal, which would be an indicator of signal leakage.

**Pull request merged**
